export interface Experience {
  title: string;
  company: string;
  period: string;
  description: string;
}

export const experiences: Experience[] = [
  {
    title: "Frontend Engineer",
    company: "Hijra Bank",
    period: "May 2022 - Present",
    description: `<ol>
      <li>As a Frontend Engineer at Hijra Bank, I am currently focusing on exciting projects to enhance our financing processes:
        <ul>
          <li>Financing Originate System (FOS) for MUAP Generator and Risk Review Generator</li>
          <li>MUAP Generator: This tool is designed to assist RM staff in generating essential documents for data collection during the financing process.</li>
          <li>Risk Review Generator: This tool supports Risk Analyst staff by streamlining the risk review process for MUAP documents generated by RM staff.</li>
        </ul>
      </li>
      <li>With these tools, we are significantly improving the documentation process for prospective and existing customers, making it more streamlined, accurate, and efficient.</li>
      <li>Additional completed projects:
        <ul>
          <li>House Financing with our Financing Originate System: I played a key role in developing a cutting-edge Financing Originate System, which transformed the house financing process. This system streamlined the financing journey, making it faster, more efficient, and user-friendly for our valued customers.</li>
          <li>Hijra Home Feature on Mobile Apps: I worked on the Hijra Home feature for our mobile apps, designed to provide an enhanced and personalized home-buying experience. With intuitive navigation, real-time updates, and interactive tools, this feature empowered potential homeowners to seamlessly find their dream homes.</li>
        </ul>
      </li>
    </ol>`,
  },
  {
    title: "Junior Web Developer",
    company: "Cindrum",
    period: "Jun 2021 - Apr 2022",
    description: `<ul>
      <li>Part of team to develop cryptocurrency webs, such as exchange web and wallet</li>
      <li>Specialized in front-end in the project</li>
      <li>Help the team to design UI/UX and convert it to the Vue project</li>
    </ul>`,
  },
  {
    title: "Internal Audit Manager",
    company: "KSP Mitra Dhuafa",
    period: "Jun 2016 - Jan 2020",
    description: `<ul>
      <li>Working on and manage a big team (35 Internal Audit Staff)</li>
      <li>Conducted strategic, technical reviews to verify compliance with quality control standards, schedule constraints, and budget parameters</li>
      <li>Gathered and analyzed financial data to determine increased fraud detection</li>
    </ul>`,
  },
  {
    title: "Management Information System Staff",
    company: "KSP Mitra Dhuafa",
    period: "May 2010 - Jun 2016",
    description: `Handled day-to-day running of Company Information System, ensuring high levels of productivity and progression. Adding some report features and fix some bugs in the system. Conducted research, gathered information from multiple sources, and presented results.

Having experience in HTML, CSS, ASP.Net

I also maintained and repaired facilities, equipment, and tools to achieve operational readiness, safety, and cleanliness. Sometimes I prepared a variety of different written communications, reports, and documents to ensure smooths operations.`,
  },
  {
    title: "Junior Programmer (Intern)",
    company: "Worxcode Imagineering Indonesia",
    period: "Jun 2009 - Dec 2009",
    description: `Be part of a big project from the company. The company's clients are several government companies, such as Pos Indonesia, the Ministry of Finance (Kementrian Keuangan), National Agency of Drug and Food Control of Indonesia (Badan POM).

Give an assist to the Senior Programmer to add some features to the project. Learn about HTML, CSS, PHP, JavaScript, and AJAX in this intern opportunity.`,
  },
];
